/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.legendary_code_challenges;

public class App {
    public static void main(String[] args) {
        System.out.println("Welcome to the LeetCode Java Playground!\n" + //
                "This application is designed for testing and running LeetCode solutions.\n" +
                "Please make sure to use appropriate test cases to validate your solutions.\n" +
                "You can add your code in the main method or create separate methods for each problem.\n" +
                "Feel free to customize this application based on your needs.\n" +
                "Happy coding!");
    }
}
